# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = ["Draft.py"]

doc_url = "https://mkarimi21.github.io/MCI_Project_Part01/"

git_url = "https://github.com/mkarimi21/MCI_Project_Part01/tree/master/"

def custom_doc_links(name): return None
