# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = []

# Cell
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Cell
from sklearn.preprocessing import MinMaxScaler




# Cell
import sweetviz as sv

# Cell
from pycaret.classification import *