# AUTOGENERATED! DO NOT EDIT! File to edit: 01_FirstDemoIntro.ipynb (unless otherwise specified).

__all__ = ['objToCat']

# Cell

import pandas as pd


# Cell

def objToCat(df):
    '''
    This function make objective column to categories and replace with int8 code

    ``` python
    ### Example

    >>> dataframe.info()
    >>> i Name_Column Len Dtype: object
    ...
    >>> objToCat(dataframe)
    >>> dataframe.info()
    >>> i Name_Column Len Dtype: int8
    ```
    '''


    len_of_type = len(df.dtypes)
    list_of_type = list(df.dtypes)

    object_type = []

    for i in range(len_of_type):
        if list_of_type[i] == 'object':
            object_type.append(df.columns[i])


    for i in range(len(object_type)):

        df[object_type[i]] = df[object_type[i]].astype('category').cat.codes

    return df

